const CONSTANT = {
  BASE_URL: `${import.meta.env.VITE_BASE_URL}/api`,
  FIREBASE_API_KEY: import.meta.env.VITE_FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID: import.meta.env.VITE_FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER,
  FIREBASE_API_ID: import.meta.env.VITE_FIREBASE_API_ID,
};

export default CONSTANT;
